---
title: "Area Project Analysis"
author: "Ethan Jantz"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RSQLite)
library(patchwork)
library(gtsummary)

sqlite.driver <- dbDriver("SQLite")

base <- "15_run_Data/Areamydatabase.db"
asym <- "15_run_Data/Asymetricalmydatabase.db"
aff <- "15_run_Data/Affluentmydatabase.db"

db_base <- dbConnect(sqlite.driver,
                     dbname = base)

db_asym <- dbConnect(sqlite.driver,
                     dbname = asym)

db_aff <- dbConnect(sqlite.driver,
                    dbname = aff)
```

```{r base}
base_table <- dbGetQuery(db_base, 'SELECT * FROM file_title')

base_table <- base_table %>%
  mutate(
    FourH_Network = gsub("x", "", FourH_Network),
    Social_Type = gsub("\n", "", Social_Type)
    )

base_analysis <- base_table %>% 
  group_by(Ticks) %>%
  summarize(
    houses_avg_endoftick = mean(Houses),
    houses_at_setup = max(Resident_Density),
    links_avg = mean(Total_Links),
    links_med = median(Total_Links),
    links_max = max(Total_Links),
    links_min = min(Total_Links),
    buyout_ratio_avg = mean(Mortgage_Buyout_Ratio),
    buyout_ratio_med = median(Mortgage_Buyout_Ratio),
    buyout_ratio_max = max(Mortgage_Buyout_Ratio),
    buyout_ratio_min = min(Mortgage_Buyout_Ratio),
    holdout_ratio_avg = mean(Hold_out_ratio),
    holdout_ratio_med = median(Hold_out_ratio),
    holdout_ratio_min = min(Hold_out_ratio),
    holdout_ratio_max = max(Hold_out_ratio),
    successes_avg = mean(Total_Success),
    fail_rate = 1 - mean(Success)
  ) %>%
  mutate(
    pct_houses_bought = houses_avg_endoftick / houses_at_setup,
    buyout_roc = (lead(buyout_ratio_avg) / buyout_ratio_avg) - 1
  )

# write_csv(base_analysis, "baseSim.csv")
```

```{r aff}
aff_table <- dbGetQuery(db_aff, 'SELECT * FROM file_title')

aff_table <- aff_table %>%
  mutate(
    FourH_Network = gsub("x", "", FourH_Network),
    Social_Type = gsub("\n", "", Social_Type)
    )

aff_analysis <- aff_table %>% 
  group_by(Ticks) %>%
  summarize(
    houses_avg_endoftick = mean(Houses),
    houses_at_setup = max(Resident_Density),
    links_avg = mean(Total_Links),
    links_med = median(Total_Links),
    links_max = max(Total_Links),
    links_min = min(Total_Links),
    buyout_ratio_avg = mean(Mortgage_Buyout_Ratio),
    buyout_ratio_med = median(Mortgage_Buyout_Ratio),
    buyout_ratio_max = max(Mortgage_Buyout_Ratio),
    buyout_ratio_min = min(Mortgage_Buyout_Ratio),
    holdout_ratio_avg = mean(Hold_out_ratio),
    holdout_ratio_med = median(Hold_out_ratio),
    holdout_ratio_min = min(Hold_out_ratio),
    holdout_ratio_max = max(Hold_out_ratio),
    successes_avg = mean(Total_Success),
    fail_rate = 1 - mean(Success)
  ) %>%
  mutate(
    pct_houses_bought = houses_avg_endoftick / houses_at_setup,
    buyout_roc = (lead(buyout_ratio_avg) / buyout_ratio_avg) - 1
  )

# write_csv(aff_analysis, "affSim.csv")
```

```{r asym}
asym_table <- dbGetQuery(db_asym, 'SELECT * FROM file_title')

asym_table <- asym_table %>%
  mutate(
    FourH_Network = gsub("x", "", FourH_Network),
    Social_Type = gsub("\n", "", Social_Type)
    )

asym_analysis <- asym_table %>% 
  group_by(Ticks) %>%
  summarize(
    houses_avg_endoftick = mean(Houses),
    houses_at_setup = max(Resident_Density),
    links_avg = mean(Total_Links),
    links_med = median(Total_Links),
    links_max = max(Total_Links),
    links_min = min(Total_Links),
    buyout_ratio_avg = mean(Mortgage_Buyout_Ratio),
    buyout_ratio_med = median(Mortgage_Buyout_Ratio),
    buyout_ratio_max = max(Mortgage_Buyout_Ratio),
    buyout_ratio_min = min(Mortgage_Buyout_Ratio),
    holdout_ratio_avg = mean(Hold_out_ratio),
    holdout_ratio_med = median(Hold_out_ratio),
    holdout_ratio_min = min(Hold_out_ratio),
    holdout_ratio_max = max(Hold_out_ratio),
    successes_avg = mean(Total_Success),
    fail_rate = 1 - mean(Success)
  ) %>%
  mutate(
    pct_houses_bought = houses_avg_endoftick / houses_at_setup,
    buyout_roc = (lead(buyout_ratio_avg) / buyout_ratio_avg) - 1
  )
# write_csv(asym_analysis, "asymSim.csv")
```

```{r analysis}
plot_holdout_avg <- function(data, title) {
  ggplot(data) +
    geom_line(aes(x = Ticks, y = holdout_ratio_avg)) +
    labs(x = "Bidding Cycles Occured", y = "Holdout Ratio",
         title = paste(title, "Scenario"),
         subtitle = "Average Holdout Ratio")
}

plot_buyout_avg <- function(data, title){
  ggplot(data) +
    geom_line(aes(x = Ticks, y = buyout_ratio_avg)) +
    scale_y_continuous(labels = scales::percent) +
    labs(x = "Bidding Cycles Occured", y = "Mortgage Buyout Ratio",
         subtitle = "Average Mortgage Buyout Ratio")
}

plot_network_avg <- function(data, title) {
  ggplot(data) +
    geom_line(aes(x = Ticks, y = links_avg)) +
    labs(x = "Bidding Cycles Occured", y = "Social Network Links",
         subtitle = "Average Number of Network Links")
}

plot_buyout_roc <- function(data, title) {
    ggplot(data) +
    geom_line(aes(x = Ticks, y = buyout_roc)) +
    scale_y_continuous(labels = scales::percent) +
    labs(x = "Bidding Cycles Occured", y = "Percent Change",
         subtitle = "Percent Change in Mortgage Buyout Ratio")
}

(plot_holdout_avg(base_analysis, "Area") + plot_buyout_avg(base_analysis, "Area") + plot_network_avg(base_analysis, "Area") +plot_buyout_roc(base_analysis, "Area"))

(plot_holdout_avg(aff_analysis, "Affluent Area") + plot_buyout_avg(aff_analysis, "Affluent Area") + plot_network_avg(aff_analysis, "Affluent Area") + plot_buyout_roc(aff_analysis, "Affluent Area"))

(plot_holdout_avg(asym_analysis, "Asymmetric Market") + plot_buyout_avg(asym_analysis, "Asymmetric Market") + plot_network_avg(asym_analysis, "Asymmetric Market") + plot_buyout_roc(asym_analysis, "Asymmetric Market"))
```

```{r tables}
sum_table <- function(data, title) {
  data %>%
  select(
    "Max Bidding Cycles" = Ticks,
    "Max Holdout Ratio" = holdout_ratio_avg,
    "Average Mortgage Buyout Ratio" = buyout_ratio_avg,
    "Pct Change in Buyout Ratio (range)" = buyout_roc
  ) %>%
  mutate(
    `Pct Change in Buyout Ratio (range)` = `Pct Change in Buyout Ratio (range)` * 100
  ) %>%
  tbl_summary(
    statistic = list(
      `Max Bidding Cycles` ~ "{max}",
      `Max Holdout Ratio` ~ "{max}",
      `Average Mortgage Buyout Ratio` ~ "{mean} ({min} - {max})",
      `Pct Change in Buyout Ratio (range)` ~ "{min} - {max}"
    ),
    missing = "no"
  ) %>%
  modify_header(
    update = list(
      label ~ paste(title, "Scenario"),
      stat_0 ~ ""
      )
  ) %>%
  modify_footnote(
    everything() ~ NA
  )
} 

gt::gtsave(as_gt(sum_table(base_analysis, "Area")), "Area Scenario Table.png")
gt::gtsave(as_gt(sum_table(aff_analysis, "Affluent Area")), "Affluent Area Table.png")
gt::gtsave(as_gt(sum_table(asym_analysis, "Asymmetrical Market")), "Asymmetrical Market Table.png")
```
